name: eval
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.7.2
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.6
  - charset-normalizer=2.1.1
  - cloudpickle=2.2.1
  - colorama=0.4.5
  - cryptography=3.4.8
  - cudatoolkit=10.2.89
  - cudnn=7.6.5.32
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.3.0
  - decorator=5.1.1
  - entrypoints=0.4
  - expat=2.5.0
  - filelock=3.0.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - future=0.18.2
  - gdown=4.6.3
  - gettext=0.21.1
  - giflib=5.2.1
  - graphite2=1.3.13
  - h5py=3.1.0
  - harfbuzz=5.3.0
  - hdf5=1.10.6
  - icu=70.1
  - imagecodecs-lite=2019.12.3
  - imageio=2.6.1
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - ipykernel=5.5.5
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - java-1.8.0-openjdk-cos7-s390x=1.8.0.242.b08
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=5.3.4
  - jupyter_core=4.5.0
  - keyutils=1.6.1
  - kiwisolver=1.3.1
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=7.87.0
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libhwloc=2.9.0
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.3.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - llvmlite=0.34.0
  - magma=2.5.2
  - matplotlib-base=3.3.4
  - mkl=2020.4
  - more-itertools=9.1.0
  - nccl=2.14.3.1
  - ncurses=6.3
  - networkx=2.7.1
  - ninja=1.11.1
  - numba=0.51.2
  - numpy=1.19.5
  - olefile=0.46
  - openjdk=8.0.332
  - openssl=1.1.1t
  - pandas=1.1.5
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=21.2.4
  - pixman=0.40.0
  - plotly=5.10.0
  - prompt_toolkit=1.0.15
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.14.0
  - pynndescent=0.5.8
  - pyopenssl=20.0.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.6.15
  - python-crfsuite=0.9.7
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytorch=1.6.0
  - pytorch-gpu=1.6.0
  - pytz=2022.7.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - pyzmq=19.0.2
  - readline=8.1.2
  - scikit-image=0.17.2
  - scikit-learn=0.24.2
  - setuptools=49.6.0
  - simplegeneric=0.8.1
  - six=1.16.0
  - sklearn-crfsuite=0.3.6
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - tabulate=0.8.10
  - tbb=2021.8.0
  - tenacity=8.2.2
  - threadpoolctl=3.1.0
  - tifffile=2020.6.3
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.1
  - traitlets=4.3.3
  - typing_extensions=4.1.1
  - umap-learn=0.5.1
  - unzip=6.0
  - wcwidth=0.2.6
  - wheel=0.37.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=0.6.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - attrs==22.1.0
    - chardet==3.0.4
    - dataclasses==0.8
    - demjson==2.2.4
    - fasttext==0.9.2
    - gensim==4.1.2
    - gitdb==4.0.10
    - gitpython==3.1.29
    - idna==2.8
    - jupyter-client==7.1.2
    - jupyter-core==4.9.2
    - nest-asyncio==1.5.6
    - nltk==3.4.1
    - pluggy==0.6.0
    - protobuf==3.19.6
    - py==1.11.0
    - pybind11==2.10.1
    - pytest==3.3.2
    - requests==2.21.0
    - scipy==1.5.4
    - smart-open==6.2.0
    - tensorboard-logger==0.1.0
    - tensorboardx==1.2
    - torch==1.0.1.post2
    - torchtext==0.11.2
    - torchvision==0.2.2
    - tqdm==4.19.9
    - urllib3==1.24.3
    - wget==3.2
