name: py2
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports.shutil_get_terminal_size=1.0.0
  - backports_abc=0.5
  - blas=1.1
  - ca-certificates=2022.12.7
  - certifi=2019.11.28
  - colorama=0.4.4
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.2
  - enum34=1.1.10
  - expat=2.5.0
  - fontconfig=2.14.0
  - freetype=2.12.1
  - functools32=3.2.3.2
  - futures=3.3.0
  - gettext=0.21.1
  - glib=2.66.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=64.2
  - ipykernel=4.10.0
  - ipython=4.2.1
  - ipython_genutils=0.2.0
  - jpeg=9e
  - jupyter_client=5.3.3
  - jupyter_core=4.6.3
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.10
  - libffi=3.2.1
  - libgcc-ng=12.1.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.66.3
  - libgomp=12.1.0
  - libgpuarray=0.7.6
  - libiconv=1.17
  - liblapack=3.9.0
  - libpng=1.6.38
  - libprotobuf=3.5.2
  - libsodium=1.0.17
  - libstdcxx-ng=12.1.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.10
  - libzlib=1.2.12
  - markupsafe=1.1.1
  - matplotlib=2.2.5
  - matplotlib-base=2.2.5
  - ncurses=6.3
  - nltk=3.2.4
  - numpy=1.15.4
  - olefile=0.46
  - openblas=0.2.20
  - openssl=1.1.1s
  - pandas=0.24.2
  - parse=1.19.0
  - pathlib=1.0.1
  - pathlib2=2.3.5
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=6.2.1
  - pip=20.1.1
  - protobuf=3.5.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pygpu=0.7.6
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=2.7.15
  - python-crfsuite=0.9.7
  - python-dateutil=2.8.1
  - python_abi=2.7
  - pytz=2019.3
  - pyyaml=5.1.2
  - pyzmq=19.0.0
  - qt=5.9.7
  - readline=8.1.2
  - scandir=1.10.0
  - scikit-learn=0.19.2
  - scipy=1.2.1
  - setuptools=44.0.0
  - simplegeneric=0.8.1
  - singledispatch=3.6.1
  - sip=4.19.8
  - six=1.16.0
  - sklearn-crfsuite=0.3.6
  - sqlite=3.39.2
  - subprocess32=3.5.4
  - tabulate=0.8.10
  - tk=8.6.12
  - tornado=5.1.1
  - tqdm=4.64.1
  - traitlets=4.3.3
  - unrar=0.4
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.2
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - boto==2.49.0
    - boto3==1.17.112
    - botocore==1.20.112
    - chardet==4.0.0
    - gensim==3.8.1
    - idna==2.10
    - jmespath==0.10.0
    - lasagne==0.2.dev1
    - mako==1.0.7
    - requests==2.27.1
    - s3transfer==0.4.2
    - sklearn-theano==0.0.1
    - smart-open==1.11.1
    - theano==1.0.5+unknown
    - urllib3==1.26.14
